### ISSUE TITLE
Json serialization error on iOS

### ISSUE THREAD

**Issue by Ronserruya** [Kirbyrawr/stellar-unity#21]
Might be related to #5 

When using the sdk on iOS, I get a json serialization error. I tried my own code, and the code in the example scene as well.

```
JsonSerializationException: Unable to find a constructor to use for type stellar_dotnet_sdk.responses.AccountResponse. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '_links', line 2, position 11.
```

full error: 
[Untitled.txt](https://github.com/Kirbyrawr/stellar-unity/files/3489945/Untitled.txt)

I tried to replace the JSON .dll with the newest portable version, but it didnt help.

ps. I re-created the account from the example scene, it was probably removed when the testnet reset.

**Comment by Kirbyrawr** [comment]
Hi there, i'm taking a look into update the SDK, hopefully soon i will have some news.

**Comment by Ronserruya** [comment]
Thanks, I forgot to mention that it does work fine on desktop and on android, just fails on iOS

**Comment by Kirbyrawr** [comment]
I believe that the problem lies in the stripping of the code by Unity when exporting to iOS, i will check it though, at first i suspected it was due to not update the SDK in a while but it doesn't seem to be the case since it supports the latest protocols of Stellar Core.

**Comment by Kirbyrawr** [comment]
I took a quick look into it and somehow the AccountResponse constructor is being stripped from the final code, i will try to fix this when i get home.

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/issues/190

**Comment by Kirbyrawr** [comment]
Gonna talk about it and see if i can fix it today.

**Comment by Ronserruya** [comment]
Thanks, I actually saw that AccountResponse only had a private constructor, thought it would be fine since it worked on android and desktop

**Comment by Kirbyrawr** [comment]
Hi there, i fixed it already, there are a couple of steps to do...

**Comment by Kirbyrawr** [comment]
Hi, can you pull the new code and test it, it should work now, i tested it in a iPad Mini 1 Gen

**Comment by Ronserruya** [comment]
This works, thanks :) 
I assume this was the solution https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html

**Comment by Kirbyrawr** [comment]
Exactly, i added a link.xml file to not strip the needed types.

**Comment by Ronserruya** [comment]
btw, you can edit the readme, since iOS is tested, and Linux works as well (that's what I use) :)

**Comment by Kirbyrawr** [comment]
Thank you for the heads up, i will update it accordingly :)!
